const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_SINGLE = 'FETCH_SINGLE';
const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
const LIKEPOST = 'LIKEPOST';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

export { CREATE, UPDATE, DELETE, FETCH_ALL, FETCH_SINGLE, FETCH_BY_SEARCH, LIKEPOST, AUTH, LOGOUT, START_LOADING, END_LOADING};
