const CREATE = 'CREATE';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const FETCH_ALL = 'FETCH_ALL';
const LIKEPOST = 'LIKEPOST';
const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

export { CREATE, UPDATE, DELETE, FETCH_ALL, LIKEPOST, AUTH, LOGOUT};
